# Config file for automatic testing at travis-ci.org
language: python

cache: pip

matrix:
    include:
      - python: 3.6
        env: TEST_TYPE="pre-commit"
      - python: 3.6
        env: TEST_TYPE="pytest" PYPI_DEPLOY=true
      - python: 3.7
        env: TEST_TYPE="pytest"
      - python: 3.6
        env: TEST_TYPE="docs" READTHEDOCS="True"

install:
  - pip install --upgrade pip wheel setuptools
  - |
      if [[ "$TEST_TYPE" == "pre-commit" ]]; then
        pip install -e .[code_style]
      fi
  - |
      if [[ "$TEST_TYPE" == "pytest" ]]; then
        pip install -e .[testing]
        pip install coveralls
      fi
  - |
      if [[ "$TEST_TYPE" == "docs" ]]; then
        pip install -e .[docs]
        url="https://github.com/jgm/pandoc/releases/tag/2.6"
        path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
        downloadUrl="https://github.com$path"
        file=${path##*/}
        wget $downloadUrl && sudo dpkg -i $file
      fi

script:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      pytest -v --cov=pytest_notebook --cov-report=
      pytest --nb-test-files docs/source/user_guide/
  fi
- |
  if [[ "$TEST_TYPE" == "pre-commit" ]]; then
    pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
  fi
- |
  if [[ "$TEST_TYPE" == "docs" ]]; then
    cd docs
    make
  fi

after_success:
- |
  if [[ "$TEST_TYPE" == "pytest" ]]; then
      coveralls
  fi

deploy:
  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: cjsewell
    password:
      secure: CiBQ7Jeus+mEORA84pQ/NuAM0TrXDfqVN6AqgaupAAPwIs59e8T10xHbHfg5NCVMNyPXQzKO7JvEpLaZMPkf+/Gieo72h8WkvLE7FOJ5ittNaHDxH+sxvurBbzPOwxXknaPiWmSbhYIyvuqJYINFu49bUSJxGeLhG7m1IG4p7QlVP48wCkZZR5iu6BAQrmcG0H0Q6Nc7mCUqQGiKySa87IiNe3Cyl+sez680niXploXtPC8OfpItByzWVa1BxTHv6XwWJJmbiu8tSmqiiLRLrWg4Ibxbw+XH5dxGIUW0jT00+5Az2LgYhN0rUJ69o2R+wCC+H/o2QD3YAKdOJjZl2wAtRIEMdtjyHa3/wyDYSc0gXyvxWF+n7L9oUnb0tLWcxDDZ1kGqNUgre7mFI1N2Dz7UAztmQgnr/75K2IPDCRs3C4VkmgkdzYS1Ivbibz2cUOt48QwIJlnwF9R7bU1ll9N1PflxwR9QeiVeQ+ZWfKIVFuF379qUFLZDxoY3GLGf0acE23O9QYw8MogrY2VDwAU75LHYwKJLWgb1U7iwA58083/Zo6DAnK+44GNlMkqYi+yJ8jGk+113x0YqoEimb3d1TtxtSSHooIjY8v5RnQfW6/e85YCmsmRi+gN0aXnUpvR2qtPwyG/k6oBwu4DsL4NybHSs1YZTh7Tmm86gmcU=
    on:
      branch: master
      tags: true
      condition: $PYPI_DEPLOY = true
